---
- name: Manage docker servers
  become: true 
  hosts: docker
  tasks:
  - name: Download docker 
    get_url:
      url:  https://get.docker.com/
      dest: /home/centos/get-docker.sh
  - name: start docker servers
    command: nohup sh /home/centos/get-docker.sh

